site_name: Code Forum Docs
site_url: https://codeforum-org.github.io/codeforum-docs/

theme:
    name: 'rtd-dropdown'
    locale: en
    highlightjs: true

markdown_extensions:
    def_list: {}
    toc:
        permalink: 
        separator: "_"
    admonition: {}